{
 "title": "kafka-connect-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All debezium metrics",
   "type": "stat",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "debezium_metrics_connected", "legendFormat": "__auto" },
    {
     "expr": "debezium_metrics_currentqueuesizeinbytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_maxqueuesizeinbytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_millisecondsbehindsource",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_millisecondssincelastevent",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_numberofcommittedtransactions",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_numberoferroneousevents",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_numberofeventsfiltered",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_queueremainingcapacity",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_queuetotalcapacity",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_remainingtablecount",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_snapshotaborted",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_snapshotcompleted",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_snapshotdurationinseconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_snapshotrunning",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_totalnumberofeventsseen",
     "legendFormat": "__auto"
    },
    {
     "expr": "debezium_metrics_totaltablecount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total events seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(debezium_metrics_totalnumberofeventsseen[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "record write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_write_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}