{
 "title": "Streaming",
 "time": { "from": "2022-08-30T04:10:22.758Z", "to": "2022-08-30T04:17:01.142Z" },
 "panels": [
  {
   "title": "queue remaining capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queueremainingcapacity{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of events seen",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "milli seconds behind source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(debezium_metrics_millisecondsbehindsource[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milli seconds since last event",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(debezium_metrics_millisecondssincelastevent{context=\"streaming\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}