services:
  connect:
    image: quay.io/yugabyte/debezium-connector:latest
    container_name: kafka-connect
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: ${KAFKA_HOST}
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my-connect-configs
      OFFSET_STORAGE_TOPIC: my-connect-offsets 
      HOST_NAME: "0.0.0.0"
      ADVERTISED_HOST_NAME: ${DOCKER_IP}
